### ISSUE TITLE
Feedback Müllkalender

### ISSUE THREAD

**Issue by violine-21** [mull-io/feedback#1]
Hi,
habe Dein Projekt gerade entdeckt. Ich finde das toll, leider kann ich es für meine Region nicht testen.
Was benötige ichvon meinem Entsorger um Deinen Service zu nutzen?
Ich glaube, mein Entsorger bietet eine ics-Datei als Müllkalender an.
Da ich zwar OpenHAB nutze aber das Kalenderbinding nicht nutze, wäre das eine tolle Alternative.

VG Andre

**Comment by lochmueller** [comment]
Hey Andre / @violine-21 
gerne eine URL zu dem Provider hier ergänzen. Dann kann ich dies einmal prüfen...
Beste Grüße,
Tim

**Comment by lochmueller** [comment]
Bisher kein Feedback bekommen. Wenn es eine Adresse/URL zum Provider gibt, gerne hier ergänzen und Ticket wieder aufmachen.
