### ISSUE TITLE
Hello, please add the location Netphen

### ISSUE THREAD

**Issue by arohleder76** [mull-io/feedback#13]
https://www.netphen.de/Rathaus-Verwaltung/Online-Service/Informationen-zur-M%C3%BCllabfuhr/

**Comment by lochmueller** [comment]
Hey @arohleder76 ,
added provider yesterday. Please make sure, that you set the city like in the form of the provider page ('Netphen-XXX').
Examples
``` 
('Setzer Weg', 'XXXX', '57250', 'Netphen-Dreis-Tiefenbach', 'DE')
('Bodelschwinghstraße', 'XXXX', '57250', 'Netphen-Netphen', 'DE') 
```
Regards,
Tim
