### ISSUE TITLE
Wolfsburg

### ISSUE THREAD

**Issue by timtschuk** [mull-io/feedback#2]
Könnt ihr Wolfsburg integrieren?
https://was-wolfsburg.de/was/abfuhrtermine.php

Wenn möglich auch gelber sack

**Comment by lochmueller** [comment]
Hey @timtschuk ,

Provider ist ergänzt. Da die Zuordnung zum Provider via ZIP passiert und die Gelben Säcke explizit einen Ortsteil brauchen, würde ich dich bitten die Adresse in Form von "Straße, Hausnummer, PLZ, Ortsteil (!!!), DE" anzugeben. Somit nicht einfach nur "Wolfsburg" als Ort eintragen.

Dann solltest du alle Infos bekommen.

Ticket schließe ich. Bei Fragen oder weitere Feedback gerne ein neues Ticket aufmachen.

Beste Grüße,
Tim
