### ISSUE TITLE
Hinzufügen Landkreis Augsburg

### ISSUE THREAD

**Issue by binderth** [mull-io/feedback#3]
Sehr cooles Projekt!

Landkreis Augsburg ist offenbar nicht unterstützt:
https://www.awb-landkreis-augsburg.de/aktuelles/abfuhrtermine

**Comment by lochmueller** [comment]
Hey @binderth 
Habe den Provider mit aufgenommen und schließe das Ticket.
Gerne einmal via Startseite prüfen....
Beste Grüße,
Tim
