### ISSUE TITLE
Abfuhrkalender Stadt Osnabrück

### ISSUE THREAD

**Issue by sholl** [mull-io/feedback#8]
Hallo, 

das ist ein interessantes Projekt. Hier gibt es die Abfallkalender der Stadt Osnabrück pro Straßenabschnitt:

https://nachhaltig.osnabrueck.de/de/abfall/muellabfuhr/muellabfuhr-digital/online-abfuhrkalender/

Vielleicht besteht ja eine Integration in Müll.io.

LG

**Comment by lochmueller** [comment]
Hallo @sholl ,

habe den Provider gerade mit aufgenommen und mache das Ticket wieder zu. Viel Spaß mit müll.io.

PS: Bitte den Straßen-Namen in Variationen prüfen "XYZ Str." geht nicht, "XYZ Straße" aber schon. Ein Mechanismus, welcher dies intern prüft, kommt in der Zukunft. Wenn somit kein Ergebnis kommt, bitte die Straße so schreiben wie auch auf der Webseite, welche du mir geschickt hast.

Ticket mache ich zu.
Freue mich immer über Feedback.

Danke,
Tim
