### ISSUE TITLE
Add Recklinghausen as Provider

### ISSUE THREAD

**Issue by ace16vitamine** [mull-io/feedback#9]
Hello,

thank you for your great API!

Please add Recklinghausen (45659) to the API, it would be really great !

Thanks
Stefan

**Comment by lochmueller** [comment]
Hey Stefan / @ace16vitamine  ,

Yes the project is leaving. But it is a side project in my free time, so I need a few days to integrate new provider. I will checked this shortly.

Regards,
Tim

**Comment by lochmueller** [comment]
Recklinghausen wurde nun mit aufgenommen. Ich schließe Das Ticket.

**Comment by ace16vitamine** [comment]
Danke !!
